const input=document.querySelector('#terminal-input'),form=document.querySelector('#form'),output=document.querySelector('#output'),terminal=document.querySelector('#terminal'),sound=document.querySelector('#sound');
const c={
help:`<b class="heading">AVAILABLE COMMANDS</b><ul><li><b>about</b> — who is behind the prompt</li><li><b>experience</b> — 29+ years in the field</li><li><b>skills</b> — capability map</li><li><b>networking</b>, <b>devops</b>, <b>development</b>, <b>security</b>, <b>ai</b>, <b>entrepreneurship</b> — focused dossiers</li><li><b>projects</b>, <b>life</b>, <b>contact</b>, <b>resume</b></li><li><b>whoami</b>, <b>date</b>, <b>clear</b></li></ul><p>Tip: use ↑/↓ for history and Tab to complete.</p>`,
about:`<b class="heading">ABOUT // NIXNINJA</b><p>Technologist, builder, operator, security-minded problem solver, and lifelong learner. I work where infrastructure, software, people, and hard problems intersect.</p><p>Understand the system. Question assumptions. Automate the repeatable. Secure the edges. Leave things better documented than you found them.</p>`,
experience:`<b class="heading">EXPERIENCE // 29+ YEARS ONLINE</b><p>Nearly three decades across the full technology stack—from cables, packets, and servers to cloud platforms, secure delivery pipelines, applications, and intelligent systems.</p><ul><li>Built and operated resilient infrastructure and networks</li><li>Led modernization, automation, and delivery improvements</li><li>Developed software and solved integration problems</li><li>Worked through both defender and adversary lenses</li><li>Turned technical ideas into practical ventures</li></ul>`,
skills:`<b class="heading">CAPABILITY MAP</b><p>${['Networking','Infrastructure','Linux','DevOps','Automation','Cloud','Software Development','Cybersecurity','Red Teaming','Penetration Testing','AI / ML','Technical Leadership','Entrepreneurship'].map(x=>`<span class="tag">${x}</span>`).join('')}</p><p>Run a focused command for more.</p>`,
networking:`<b class="heading">NETWORKING + INFRASTRUCTURE</b><p>Designing, troubleshooting, and hardening routing, switching, wireless, firewalls, segmentation, virtualization, servers, storage, and the practices that keep it all dependable.</p>`,
devops:`<b class="heading">DEVOPS + AUTOMATION</b><p>Building reliable paths from idea to production with infrastructure as code, CI/CD, containers, observability, configuration management, and pragmatic automation.</p>`,
development:`<b class="heading">DEVELOPMENT</b><p>Creating useful software, scripts, integrations, APIs, and web experiences—choosing technology to fit the problem rather than the fashion cycle.</p>`,
security:`<b class="heading">CYBERSECURITY // RED TEAM // PENTESTING</b><p>Thinking like an attacker to build stronger defenses: reconnaissance, vulnerability analysis, penetration testing, adversary simulation, hardening, and clear remediation.</p><p class="muted">Authorized environments only. Curiosity and ethics are part of the toolkit.</p>`,
ai:`<b class="heading">AI + MACHINE LEARNING</b><p>Applying modern AI, intelligent workflows, and machine learning to amplify human capability—without losing sight of security, reliability, privacy, or the real problem.</p>`,
entrepreneurship:`<b class="heading">ENTREPRENEURSHIP</b><p>Turning rough ideas into working systems and viable ventures: finding the constraint, prototyping quickly, wearing every hat, and balancing ambition with value.</p>`,
projects:`<b class="heading">PROJECTS // CURATED, NOT CRAWLED</b><p>Selected case studies are being prepared for public release. This portfolio intentionally does not enumerate GitHub repositories or expose private work.</p><ul><li>Infrastructure and automation systems</li><li>Security research and defensive tooling</li><li>AI-assisted workflows and experiments</li><li>Software products and entrepreneurial builds</li></ul><p class="muted">More signal, less feed. Check back soon.</p>`,
life:`<b class="heading">ADVENTURE // LIFE OUTSIDE THE SHELL</b><p>Exploration, adventure, learning, and time away from the screen keep perspective sharp. Whether the route leads outdoors, somewhere unfamiliar, or into a new discipline: stay curious and keep moving.</p>`,
contact:`<b class="heading">CONTACT // OPEN A CHANNEL</b><p>The cleanest public route is GitHub:</p><p><a href="https://github.com/jmtibbetts" target="_blank" rel="noopener">github.com/jmtibbetts ↗</a></p><p class="muted">No address harvesting. No auto-exposed private data.</p>`,
resume:`<b class="heading">RESUME // PLACEHOLDER</b><p>The downloadable resume is being prepared. Until then, run <button class="inline" data-command="experience">experience</button>, <button class="inline" data-command="skills">skills</button>, or <button class="inline" data-command="contact">contact</button>.</p>`,
whoami:`<p>root — because some problems require full context.</p>`,date:()=>`<p>${new Date()}</p>`};
const aliases={ls:'help',man:'help','?':'help',bio:'about',stack:'skills',cybersecurity:'security',pentest:'security','red-team':'security','ai/ml':'ai',ml:'ai',adventure:'life',github:'contact'},names=[...Object.keys(c),'clear'];let history=JSON.parse(sessionStorage.getItem('history')||'[]'),hi=history.length,audio;
function beep(f=520,d=.025){if(sound.getAttribute('aria-pressed')!=='true')return;audio||=new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.018;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function esc(v){let n=document.createElement('div');n.textContent=v;return n.innerHTML}function run(raw){let entered=raw.trim();if(!entered)return;history.push(entered);history=history.slice(-50);hi=history.length;sessionStorage.setItem('history',JSON.stringify(history));let name=aliases[entered.toLowerCase()]||entered.toLowerCase();if(name==='clear'){output.innerHTML='';input.value='';return}let block=document.createElement('div'),result=c[name];block.innerHTML=`<div class="echo">${esc(entered)}</div><div class="response">${result?(typeof result==='function'?result():result):`<p class="error">command not found: ${esc(entered)}</p><p>Type <b>help</b> to list commands.</p>`}</div>`;output.append(block);input.value='';beep(result?620:180,.04);terminal.scrollTo({top:terminal.scrollHeight,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'})}
form.addEventListener('submit',e=>{e.preventDefault();run(input.value)});document.addEventListener('click',e=>{let b=e.target.closest('[data-command]');if(b){run(b.dataset.command);input.focus()}});terminal.addEventListener('click',e=>{if(!e.target.closest('a,button,input'))input.focus()});input.addEventListener('keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();hi=Math.max(0,Math.min(history.length,hi+(e.key==='ArrowUp'?-1:1)));input.value=history[hi]||''}if(e.key==='Tab'){e.preventDefault();let m=names.filter(n=>n.startsWith(input.value.toLowerCase()));if(m.length===1)input.value=m[0]}beep(430,.012)});sound.addEventListener('click',()=>{let on=sound.getAttribute('aria-pressed')!=='true';sound.setAttribute('aria-pressed',on);sound.textContent=`SOUND: ${on?'ON':'OFF'}`;if(on)beep(720,.06)});function tick(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}tick();setInterval(tick,1000);
